rhymojs/rhymojs

CONTRIBUTING.md

Add '-b' flag to checkout command because it has to create a new branch.

Fix checkout command

---

.github/workflows/continous-integration.yml

Change key `pull` to `pull_request` to actually listen for pull requests.

fix: change key `pull` to `pull_request`

---

src/index.ts
src/useLockScroll/index.ts
src/useLockScroll/useLockScroll.ts

Prevents users from scrolling if the state is true.

feat: useLockScroll

---

.eslintrc.json
package.json
yarn.lock

Manage import order leveraging ESLint to keep this library maintainable and readable.

feat: manage import order

---

package.json

Change URL `https://github.com/xeptao/rhymojs` to `https://github.com/rhymojs/rhymojs`

fix: repository url

---

CHANGELOG.md
package.json

chore(release): `v1.4.1`

---

.npmignore
.storybook/main.js
.storybook/preview.js
package.json
yarn.lock

Setup storybook to start writing components.
Issue Close #42

feat: setup storybook

---

.npmignore

Prevent npm from publishing config files.

refactor: add `babel.config.js` to `.npmignore`

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Added issue templates to keep everything more clean and maintainable.

feat: issue templates

---

tests/useGeolocation.test.ts

Validate IP adresses with the help of Regular Expressions.

feat: ip validator

---

tests/useGeolocation.test.ts

Change the Regular Expression to a faster and a stricter one.

fix: ip regular expression

---

src/useLocalStorage/useLocalStorage.ts
tests/useLocalStorage/useLocalStorage.test.tsx

useLocalStorage was always setting the initial value to '""'.
Issue Close #65

fix: remember value on refresh

---

src/index.ts
src/useToggle/index.ts
src/useToggle/useToggle.ts
tests/useToggle/Test.tsx
tests/useToggle/useToggle.test.tsx

Added a new feature  **useToggle**  which returns a `boolean` value and a `function` to reverse the current `boolean` value.
Also performed tests on this new feature of which all passed (#26)

Swarup4741/[feature] - useToggle

---

CHANGELOG.md
package.json

Generated changelog for the version `v1.5.0`.
- Change the `version` key in `package.json` to `1.5.0`.
- Generate a changelog for the version.
This is only the changelog and package.json, we will have to create a tag and push the changes to the `prod branch`
No related issues.

chore(release): v1.5.0

---

package.json

Added more keywords to hopefully attract more users to this library.
- Add more strings to the key `keywords` in `package.json`

refactor: add keywords

---

src/makeRandomString/makeRandomString.ts
src/toCapitalizeCase/toCapitalizeCase.ts
src/uniqueArray/uniqueArray.ts
src/useClipboard/useClipboard.ts
src/useGeolocation/useGeolocation.ts
src/useLocalStorage/useLocalStorage.ts
src/useLockScroll/useLockScroll.ts
src/useQuery/useQuery.ts
src/useScrollPosition/useScrollPosition.ts
src/useTheme/useTheme.ts
src/useToggle/useToggle.ts
src/useWindowSize/useWindowSize.ts

Removed key `version` from every JSDoc.
- Removed key `version` from every JSDOC
Issue Close #80

fix: remove key 'version' from every jsdoc

---

README.md
SECURITY.md
src/makeRandomString/makeRandomString.ts
src/toCapitalizeCase/toCapitalizeCase.ts
src/uniqueArray/uniqueArray.ts
src/useClipboard/useClipboard.ts
src/useGeolocation/useGeolocation.ts
src/useLocalStorage/useLocalStorage.ts
src/useLockScroll/useLockScroll.ts
src/useQuery/useQuery.ts
src/useScrollPosition/useScrollPosition.ts
src/useTheme/useTheme.ts
src/useWindowSize/useWindowSize.ts

We are ditching the idea to have a website.
Issue Close #104

refactor: remove all website references

---

.github/FUNDING.yml

Removed website from funding links
- Remove "custom" from FUNDING.yml
Removed website from funding links  because we ditched the website.

fix: funding links

---

DOCUMENTATION.md

Added documentation that will help the users understand what the functions really do.
- Created a file called `DOCUMENTATION.md`
Issue Close #106

feat: docs for features

---

CONTRIBUTING.md
scripts/contribute.sh

Added a shell script that will help you contribute to Rhymo.
- create file `scripts/contribute.sh`
- change file `DOCUMENTATION.md` to add the new features

feat: contribution script

---

tests/useGeolocation.test.ts

Make the test able to use 6 seconds instead of 5.
- change `tests/useGeolocation.test.ts`

fix: increase test time to make it less error-prone
